### ISSUE TITLE
All names for parameters should be allowed

### ISSUE THREAD

**Issue by evanunderscore** [evanunderscore/defopt#17]
http://www.sphinx-doc.org/en/stable/domains.html#info-field-lists

> `param`, `parameter`, `arg`, `argument`, `key`, `keyword`: Description of a parameter.

Currently only `param` is accepted.

**Comment by evanunderscore** [comment]
Should also handle `kwtype` which `sphinxcontrib-napoleon` uses to add types to keyword arguments. Support for this was added to Napoleon between 0.5.0 and 0.5.1 and appears to have slipped past the changelog (heads up @RobRuana in case you want to retroactively add that).

**Comment by RobRuana** [comment]
Thanks for catching that, I've updated the [CHANGES file](https://bitbucket.org/birkenfeld/sphinx-contrib/commits/7e91c349bea09398ce8278543a791991297cfa7f).

**Comment by evanunderscore** [comment]
Thanks!
