### ISSUE TITLE
Rendering rst docstrings to the terminal with bold/underline(/italic)

### ISSUE THREAD

**Issue by anntzer** [evanunderscore/defopt#22]
A quick suggestion: render bold/italic markup in rst docstrings in the terminal using e.g. colorama, or blessings (which can do underline/italics).

**Comment by evanunderscore** [comment]
Cool idea. I'm fine with a solution that doesn't work on Windows as long as it doesn't break it.

**Comment by evanunderscore** [comment]
Added in #24 and #25.
