### ISSUE TITLE
Make defopt._create_parser / defopt._call_function public?

### ISSUE THREAD

**Issue by anntzer** [evanunderscore/defopt#35]
This would be convenient for further customization.  Additional points if it takes the ArgumentParser object as first argument (it can always directly set the `formatter_class` attribute itself).

defopt._call_function would also need to be public so that we can actually make use of the result of the argument-line parsing of course.

**Comment by evanunderscore** [comment]
This probably ties in to a lot of the discussion on #7. Are there any particular use cases you're wanting to support?

**Comment by anntzer** [comment]
I was hoping to set the `epilog` kwarg/attribute of the parser, which is not really a big thing... most designs should work for that.

**Comment by anntzer** [comment]
Actually I can just do something like `argparse.ArgumentParser = partial(argparse.ArgumentParser, epilog=...)` which is a bit hacky but works (the monkeypatching should be fine as you expect only one ArgumentParser to be constructed throught the lifetime of the program, and if you really care you can always revert it), so feel free to close this issue.

**Comment by evanunderscore** [comment]
That sounds like a good workaround but as you said is a bit hacky. I'll leave this issue open for now.

**Comment by anntzer** [comment]
I think this is mostly closed by #60.
