### ISSUE TITLE
Supporting nargs using Tuple, and nargs+metavar using NamedTuple

### ISSUE THREAD

**Issue by anntzer** [evanunderscore/defopt#37]
I'd like to propose that
```
@defopt.run
def main(x: Tuple[int, str]): ...
```
creates an argument, `x`, with `nargs=2`, with each argument converted using the correct type (in the function, `x` would indeed be a tuple), and that
```
@defopt.run
def main(x: NamedTuple('T', [('foo', int), ('bar', str)])): ...
```
does the same but additionally uses `(foo, bar)` as the metavar for `x` (specifically, this would check that the annotation is a subclass of tuple and defines `__annotation__`).  (And likewise, when the function is actually called, `x` would be of type `T`.)

**Comment by evanunderscore** [comment]
Sounds good to me. I'll take a look at the PR when I get some spare time.
