### ISSUE TITLE
For subcommand names, replace underscores by dashes

### ISSUE THREAD

**Issue by anntzer** [evanunderscore/defopt#44]
Options already implicitly replace underscores in their names by dashes in the CLI.  For consistency, it would be appreciated if subcommands did the same.  The options I see are

- break backcompatibilty and make this nonconfigurable.
- make this configurable (seems a bit overkill and inconsistent with the behavior for flags)
- hack into add_subparsers to map both `./foo.py bar_baz` and `./foo.py bar-baz` to the same function, preferably while displaying only one of them in the help string.

**Comment by evanunderscore** [comment]
For simplicity I'm fine with breaking backwards compatibility and bumping the major version.

**Comment by anntzer** [comment]
We may need to be careful with subcommand names that currently start with an underscore, though.
