### ISSUE TITLE
Support bullet and enumerated lists in markup

### ISSUE THREAD

**Issue by anntzer** [evanunderscore/defopt#45]
Currently, bullet and enumerated lists in a docstring get deleted in the rendered help.  This is because they have an `element.tag` set to `bullet_list` and `enumerated_list` respectively, whereas parse_docstring only handles `paragraph` and `literal_block` and silently discards everything else.  It should be "relatively" easy to render such xml elements correctly.
More generally, I would also suggest triggering a warning when an xml element gets discarded.

**Comment by evanunderscore** [comment]
Sounds good to me.

**Comment by anntzer** [comment]
Closed by #47, which now *errors* on discarded xml elements (which I think is a better default -- we can always revisit if that turns out to be too harsh).

**Comment by evanunderscore** [comment]
Agreed, this was my approach with untyped parameters instead of defaulting to string as most other similar parsers do. Silently discarding elements was an oversight rather than an intentional decision.
